/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as AuthenticatedMeuEspacoRouteImport } from './routes/_authenticated/meu-espaco'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeuEspacoRoute = AuthenticatedMeuEspacoRouteImport.update({
  id: '/meu-espaco',
  path: '/meu-espaco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/meu-espaco': typeof AuthenticatedMeuEspacoRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/meu-espaco': typeof AuthenticatedMeuEspacoRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/_authenticated/meu-espaco': typeof AuthenticatedMeuEspacoRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/servicos'
    | '/meu-espaco'
    | '/projetos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/servicos'
    | '/meu-espaco'
    | '/projetos/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comunidade'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/servicos'
    | '/_authenticated/meu-espaco'
    | '/projetos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComunidadeRoute: typeof ComunidadeRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meu-espaco': {
      id: '/_authenticated/meu-espaco'
      path: '/meu-espaco'
      fullPath: '/meu-espaco'
      preLoaderRoute: typeof AuthenticatedMeuEspacoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeuEspacoRoute: typeof AuthenticatedMeuEspacoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeuEspacoRoute: AuthenticatedMeuEspacoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComunidadeRoute: ComunidadeRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
